// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_BssysV18ZoA6jgE8TmbjBNLrNhB13S0',
    appId: '1:47201384988:web:21882f8697bbd7393efdd9',
    messagingSenderId: '47201384988',
    projectId: 'hailolaa-mynotes-project',
    authDomain: 'hailolaa-mynotes-project.firebaseapp.com',
    storageBucket: 'hailolaa-mynotes-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCca1764jT5AP490WiBLYaugr9dx7F0HPc',
    appId: '1:47201384988:android:8b980746ba6ed60c3efdd9',
    messagingSenderId: '47201384988',
    projectId: 'hailolaa-mynotes-project',
    storageBucket: 'hailolaa-mynotes-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu9D-J1k1hK5o3meYSqdNi3yM2IlvQvmI',
    appId: '1:47201384988:ios:e09110bd8954ffab3efdd9',
    messagingSenderId: '47201384988',
    projectId: 'hailolaa-mynotes-project',
    storageBucket: 'hailolaa-mynotes-project.firebasestorage.app',
    iosBundleId: 'com.example.myNotebook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu9D-J1k1hK5o3meYSqdNi3yM2IlvQvmI',
    appId: '1:47201384988:ios:e09110bd8954ffab3efdd9',
    messagingSenderId: '47201384988',
    projectId: 'hailolaa-mynotes-project',
    storageBucket: 'hailolaa-mynotes-project.firebasestorage.app',
    iosBundleId: 'com.example.myNotebook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_BssysV18ZoA6jgE8TmbjBNLrNhB13S0',
    appId: '1:47201384988:web:16b6436587baeb643efdd9',
    messagingSenderId: '47201384988',
    projectId: 'hailolaa-mynotes-project',
    authDomain: 'hailolaa-mynotes-project.firebaseapp.com',
    storageBucket: 'hailolaa-mynotes-project.firebasestorage.app',
  );

}